/****************************** Module Header ******************************\
*
* Module Name: OS2.H
*
* This is the top level include file that includes all the files necessary
* for writing an OS/2 application.
*
* Copyright (c) International Business Machines Corporation 1981, 1988-1990
*
\***************************************************************************/

#define OS2_INCLUDED

/* Common definitions */

#include <os2def.h>

/* OS/2 Base Include File */

#include <bse.h>

/* OS/2 Presentation Manager Include File */

#include <pm.h>

