#include "WATCOM100A-FIXES.h"

#include "H\malloc.h"

#define __WATCOMC__ 1000
#define __386__
#define __DOS__

#define __cplusplus
#include "H\dos.h"
#undef __cplusplus

#include "H\stdlib.h"
#include "H\stdio.h"
#include "H\conio.h"
#include "H\fcntl.h"

#include "H\io.h"
#include "H\mem.h"
#include "H\math.h"
#include "H\time.h"
#include "H\SYS\stat.h"
#include "H\SYS\types.h"
#include "H\assert.h"

